### PR TITLE
Add framework for new pages

### PR DESCRIPTION
**Pull request by BenWalker01**
as per title

### CODE REVIEW

**Review by TameU — APPROVED** [review]
Looks good to me! Updating documentation.html at the moment and shall request some more reviews once I've got that done

**Review by BenWalker01 — COMMENTED** [review]
image
Doesn't seem to work. Image scaled wrong, navbar hides title. Perhaps a more established difference between the required docs and the other stuff

**Review by TameU — APPROVED** [review]
Fixes:
- Background image set to be fixed on screen
- Updated href colour to stand out from background
Additions:
- Added documentation PDFs to new section
- Architecture and Implementation PDFs to be added

**Comment by BenWalker01** [comment]
> Fixes:
> 
>     * Background image set to be fixed on screen
> 
>     * Updated href colour to stand out from background
>       Additions:
> 
>     * Added documentation PDFs to new section
> 
>     * Architecture and Implementation PDFs to be added

What are you approving???

**Comment by TameU** [comment]
> > Fixes:
> > ```
> > * Background image set to be fixed on screen
> > 
> > * Updated href colour to stand out from background
> >   Additions:
> > 
> > * Added documentation PDFs to new section
> > 
> > * Architecture and Implementation PDFs to be added
> > ```
> 
> What are you approving???

I accidentally set myself to re-review earlier so I added these as comments to say what I updated, should've just been a comment rather than an approval

**Comment by TameU** [comment]
> image Doesn't seem to work. Image scaled wrong, navbar hides title. Perhaps a more established difference between the required docs and the other stuff

Image is scaling fine on my device? Are you on the update branch? I'll improve on the difference with the documentation section now

**Comment by BenWalker01** [comment]
Am on the up to date update branch, as apparent in the screenshot. Using firefox. The page is scrolled all the way to the top

**Comment by TameU** [comment]
Ah yes of course. Very strange but currently having a look into it

**Comment by TameU** [comment]
Background is set to cover the whole page and is centred and fixed. I have no clue why the image could be scaling wrong so maybe a screenshare over call would help figure this out

**Pull request merged**
