### PR TITLE
Updated download href

### PR DESCRIPTION
**Pull request by TameU**

### CODE REVIEW

**Review by BenWalker01 — COMMENTED** [review]
that won't fix it

**Comment by BenWalker01** [comment]
change the name in name.txt. That link gets immediately over written @TameU

**Comment by TameU** [comment]
Thats strange, name.txt seems fine

**Comment by TameU** [comment]
Ohhhhh nevermind there's a dash missing

**Review by BenWalker01 — APPROVED** [review]

**Pull request merged**
